#!/usr/bin/env Rscript

#########
# NOTES #
#########
# This code was used to produce Figure 5 of the Ensemblux manuscript

########
# Main #
########
## Load libraries
packages <- c('dplyr', 'tidyr' 'pdfCluster', 'data.table','readr','lubridate', 'tidyverse', 'moments', 'mousetrap', 'usethis', 'devtools', 'desc', 'kneedle', 'ROCit', 'ggplot2', 'factoextra', 'ggpubr', 'ComplexUpset', 'Seurat', 'Matrix', 'scCustomize', 'vctrs', 'fossil', 'openxlsx', 'stringr', 'MAST' )
lapply(packages, library, character.only = TRUE)

output_dir= '~/ensemblux_manuscript/Figure6'

######################################################
# Integrate, cluster, and ARI for NSC Seurat objects #
######################################################
## code
    ## Load Step 4 Seurat object generated by scRNAbox
    seu_r1 <- readRDS('~/NSC/pool1/step4/objs4/Pool1.rds')
    df_r1 <- data.frame(seu_r1@meta.data)
    seu_r2 <- readRDS('~/NSC/pool2/step4/objs4/Pool2.rds')
    df_r2 <- data.frame(seu_r2@meta.data)

    ## Load corresponding Ensemblux outputs
    ensemblux_r1 <- read.delim("~/NSC/pool1/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
    rownames(ensemblux_r1) <- paste0("Pool1_", ensemblux_r1$barcode)
    rownames(ensemblux_r1) == rownames(df_r1)
    ensemblux_r2 <- read.delim("~/NSC/pool2/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
    rownames(ensemblux_r2) <- paste0("Pool2_", ensemblux_r2$barcode)
    rownames(ensemblux_r2) == rownames(df_r2)

    ## Merge Seurat and Ensemblux
    seu_r1 <- AddMetaData(seu_r1, ensemblux_r1)
    seu_r2 <- AddMetaData(seu_r2, ensemblux_r2)
   
    ## Prepare Seurat objects for integration
    DefaultAssay(seu_r1) <- 'RNA'
    seu_r1<- NormalizeData(seu_r1,normalization.method = "LogNormalize", scale.factor =10000) ##new code
    seu_r1<- FindVariableFeatures(seu_r1, selection.method = "vst", nfeatures = 2500)
    seu_r1<- ScaleData(seu_r1, verbose = FALSE)

    DefaultAssay(seu_r2) <- 'RNA'
    seu_r2<- NormalizeData(seu_r2,normalization.method = "LogNormalize", scale.factor =10000) ##new code
    seu_r2<- FindVariableFeatures(seu_r2, selection.method = "vst", nfeatures = 2500)
    seu_r2<- ScaleData(seu_r2, verbose = FALSE)

    seu_list <- list(seu_r1 = seu_r1, seu_r2 = seu_r2)
        
    ## Select inetgration features
    features <- Seurat::SelectIntegrationFeatures(object.list = seu_list, nfeatures = 2500)

    ## Find integration anchors
    seu_anchors <- Seurat::FindIntegrationAnchors(object.list = seu_list, dims = 1:25, anchor.features = features)

    ## Integrate Seurat objects
    seu_int <- Seurat::IntegrateData(anchorset = seu_anchors,dims = 1:25)

    ## Set default assay to integrated
    Seurat::DefaultAssay(seu_int) <- "integrated"

    ## Scale integrated Seurat object
    seu_int <- ScaleData(seu_int, verbose = FALSE)

    ## Run PCA and UMAP on integrated Seurat object
    seu_int <- RunPCA(seu_int, npcs = 25, verbose = FALSE)
    seu_int <- RunUMAP(seu_int, dims = 1:25, n.neighbors =45)

    ## Cluster across clustering resolutions
    par_FindClusters_resolution <- c(0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)
    seu_int <- FindNeighbors(seu_int,  dims = 1:25, k.param = 45, prune.SNN = 1/15)
    seu_int <- Seurat::FindClusters(seu_int, resolution = par_FindClusters_resolution)
    seu_int <- RunUMAP(seu_int, dims = 1:25)

    ## Print UMAPs at different resolutions
    for (i in par_FindClusters_resolution){
        Seurat::DimPlot(seu_int, group.by = paste("integrated_snn_res.",i,sep=''))
        ggsave(paste(output_dir,"/integrated_snn_res.",i,".pdf",sep=""))
    }

    ### Compute clustering-specific ARI
    par_RI_reps <- 25

    ## set default assay
    par_whatAssay <- "integrated"
    Seurat::DefaultAssay(seu_int) <- "integrated"

    ## create output directory for ARI outputs
    OUT_DIR <- output_dir 

    ## Function to run louvain clustering multiple times and calculate ARI
    calculate_rand_index <- function(seu_object, par_FindClusters_resolution, OUT_DIR) {
        mybiglist <- list()
        means <- list()
        standard_devs <- list()
        result <- list()
        reps = par_RI_reps
        for(i in par_FindClusters_resolution) { 
            for(n in 1:reps) { 
            seu_object <- Seurat::FindClusters(seu_int, resolution = i, random.seed = n) 
            # retrieve the clustering
            column <- paste0(par_whatAssay,"_snn_res.",i)
            df <- data.frame(seu_object@meta.data)
            df1 <- df %>% select(column)
            result[[n]] <- df1[,1]
            }
            mybiglist <- list()
            for (f in 1:length(result)){
            for (j in 1:length(result)){
                if (f==j) {
                name <- paste0(f, ",", j)
                tmp <- -5  
                mybiglist[[name]] <- tmp
                mybiglist
                } else {
                name <- paste0(f, ",", j)
                tmp <- adj.rand.index(result[[f]], result[[j]])
                mybiglist[[name]] <- tmp
                mybiglist
                }
            }
            }
            mybiglist_test <-  mybiglist[mybiglist != -5]
            
            mean <- mean(unlist((mybiglist_test)))
            sd <- sd(unlist((mybiglist_test)))
            means[[paste0("mean_",i)]] <- mean                           
            standard_devs[[paste0("sd_",i)]] <- sd                            
        }
        ## standard deviation
        # plot standard deviation
        sd_df<- data.frame(standard_devs)
        sd_df<- data.frame(t(sd_df))
        sd_df$resolution <- rownames(sd_df)
        colnames(sd_df) <- c("sd", "Resolution")
        sd_df$group = "group"
        sd_plot <- ggplot(sd_df, aes(x = Resolution, y = sd, group = group)) +
            geom_line() + geom_point() + theme_bw() +
            theme(axis.text.x = element_blank(),
                axis.title.x = element_blank(),
                axis.ticks.x = element_blank()) +
                ylab("SD ARI")
        ## means
        # plot means
        sd_mean<- data.frame(means)
        sd_mean<- data.frame(t(sd_mean))
        sd_mean$resolution <- rownames(sd_mean)
        colnames(sd_mean) <- c("mean", "Resolution")
        sd_mean$group = "group"
        mean_plot <- ggplot(sd_mean, aes(x = Resolution, y = mean, group = group)) +
            geom_line() + geom_point() + theme_bw() +
            theme(axis.text.x = element_blank(),
                axis.title.x = element_blank(),
                axis.ticks.x = element_blank()) +
                ylab("Mean ARI")

        ## arrange plots
        ggarrange(mean_plot, sd_plot, ncol = 1, nrow = 2)
        # Combine standard deviation and means list
        list3 <- c(means,standard_devs)
        list3_df <- data.frame(list3)
        list3_df
        # Write excel file
        if(file.exists(paste(OUT_DIR, "/clustering_ARI.xlsx", sep=''))){
            file.remove(paste(OUT_DIR, "/clustering_ARI.xlsx", sep=''))
        }
        write.xlsx(list3_df, paste(OUT_DIR, "/clustering_ARI.xlsx", sep='')) 
        plots <- ggarrange(mean_plot, sd_plot, ncol = 1, nrow = 2, align = "hv")
        plots
    }  

    ## Compute standard deviation and mean of ARI at different clustering resolutions
    test_plot <- calculate_rand_index(seu_int,par_FindClusters_resolution, OUT_DIR ) 

    ## function to plot ARI information and cluster resolution together
    calculate_clusters<- function(seu_int, par_FindClusters_resolution, test_plot, OUT_DIR) {
        mybiglist <- list()
        for(i in par_FindClusters_resolution) { 
            column <- paste0(par_whatAssay,"_snn_res.",i)
            df <- data.frame(seu_int@meta.data)
            df1 <- df %>% select(column)
            n_levels <-length(unique(df1[,1]))
            mybiglist[[column]] <- n_levels
        }
        mybiglist
        sd_df<- data.frame(mybiglist)
        sd_df<- data.frame(t(sd_df))
        sd_df$resolution <- rownames(sd_df)
        colnames(sd_df) <- c("cluster", "Resolution")
        sd_df$group = "group"
        cluster_plot <- ggplot(sd_df, aes(x = Resolution, y = cluster, group = group)) +
            geom_line() +
            geom_point() +
            theme_bw() +
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            ylab("Number of clusters")
        ggarrange(test_plot, cluster_plot, ncol = 1, nrow = 2, heights = c(1.25,1))
        ggsave(file = paste(OUT_DIR, "/ARI.pdf", sep=''))
    }  

    ## Produce final plot for ARI
    calculate_clusters(seu_int, par_FindClusters_resolution, test_plot, OUT_DIR) 

##

######################################
# Add putative cell type annotations #
######################################
## code
    ## Add an annotation
    par_level_genotype <- "Sample_ID"
    par_annotate_resolution <- 'integrated_snn_res.0.25'
    cluster.ids<-c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_POU5F1", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "NPC_MEF2C", "NSC_APOA1")
    par_name_metadata <- "resolution_0.25_broad_refined_DEG"

    ## Set cell identity to the clustering resolution defined by the user
    Idents(seu_int) <- par_annotate_resolution

    ## Set cluster resolution and rename cluster identities
    seu_int <- SetIdent(seu_int, value = par_annotate_resolution)
    names(cluster.ids) <- levels(seu_int)    
    seu_int <- RenameIdents(seu_int, cluster.ids) 
    seu_int$temp_temp_1 <- Idents(seu_int)

    name_meta <- names(seu_int@meta.data) 
    length <- length(name_meta)
    name_meta[length] <- par_name_metadata
    names(seu_int@meta.data) <- name_meta

    ## Save annotated Seurat object    
    saveRDS(seu_int,paste(output_dir,'/NSC_annotated_seurat.rds', sep=''))

    ## Save query Seurat object with reference annotation predicitions
    DimPlot(seu_int, reduction = "umap", label = FALSE, pt.size = 0.1, raster = FALSE) + 
        NoLegend() +  
        theme_void() + 
        scale_color_manual(values = c(
        "Glia" = "#A6CEE3",
        "NSC_SOX2"="#1F78B4",
        "NPC_POU5F1"="#B2DF8A",
        "Neurons_DCX"="#33A02C",
        "Neurons_GRIA1"="#FB9A99",
        "NPC_S100B"="#E31A1C",
        "NPC_MEF2C"="#FDBF6F",
        "NSC_APOA1"="#FF7F00"))
    ggsave(file = paste(output_dir, "/resolution_0.25_cluster_annotation_NSC.pdf", sep=''))
##

###########################################################
# Clustering-resolution specific Adjusted Rand Index plot #
###########################################################
## code
    ## Ensemblux NSC
    ensemblux <- read.xlsx('~/ensemblux_manuscript/Figure5/ADHD_NSC_ensemblux_500/clustering_ARI.xlsx')
    ensemblux <- data.frame(ensemblux)
    mean <- list(ensemblux[,1:20])
    mean <- unlist(mean)
    mean <- unname(mean)
    sd <- list(ensemblux[,21:ncol(ensemblux)])
    sd <- unlist(sd)
    sd <- unname(sd)
    res <- colnames(ensemblux[,1:20])
    res <- c(res)
    res <- gsub(".*_","",res)
    #res <- as.numeric(res)
    ensemblux <- data.frame(mean, sd, res)
    ensemblux <- na.omit(ensemblux)
    ensemblux$class <- "Ensemblux"

    ## Demuxlet NSC
    demuxlet <- read.xlsx('~/ensemblux_manuscript/Figure5/ADHD_NSC_demuxlet_500/clustering_ARI.xlsx')
    demuxlet <- data.frame(demuxlet)
    mean <- list(demuxlet[,1:20])
    mean <- unlist(mean)
    mean <- unname(mean)
    sd <- list(demuxlet[,21:ncol(demuxlet)])
    sd <- unlist(sd)
    sd <- unname(sd)
    res <- colnames(demuxlet[,1:20])
    res <- c(res)
    res <- gsub(".*_","",res)
    demuxlet <- data.frame(mean, sd, res)
    demuxlet <- na.omit(demuxlet)
    demuxlet$class <- "Demuxlet"

    ## None NSC
    none <- read.xlsx('~/ensemblux_manuscript/Figure5/ADHD_NSC_none_500/clustering_ARI.xlsx')
    none <- data.frame(none)
    mean <- list(none[,1:20])
    mean <- unlist(mean)
    mean <- unname(mean)
    sd <- list(none[,21:ncol(none)])
    sd <- unlist(sd)
    sd <- unname(sd)
    res <- colnames(none[,1:20])
    res <- c(res)
    res <- gsub(".*_","",res)
    none <- data.frame(mean, sd, res)
    none <- na.omit(none)
    none$class <- "None"

    ## DF NSC
    doubletfinder <- read.xlsx('~/ensemblux_manuscript/Figure5/ADHD_NSC_DF_500/clustering_ARI.xlsx')
    doubletfinder <- data.frame(doubletfinder)
    mean <- list(doubletfinder[,1:20])
    mean <- unlist(mean)
    mean <- unname(mean)
    sd <- list(doubletfinder[,21:ncol(doubletfinder)])
    sd <- unlist(sd)
    sd <- unname(sd)
    res <- colnames(doubletfinder[,1:20])
    res <- c(res)
    res <- gsub(".*_","",res)
    doubletfinder <- data.frame(mean, sd, res)
    doubletfinder <- na.omit(doubletfinder)
    doubletfinder$class <- "DF"

    ## Demuxalot NSC
    demuxalot <- read.xlsx('~/ensemblux_manuscript/Figure5/ADHD_NSC_demuxalot_500/clustering_ARI.xlsx')
    demuxalot <- data.frame(demuxalot)
    mean <- list(demuxalot[,1:20])
    mean <- unlist(mean)
    mean <- unname(mean)
    sd <- list(demuxalot[,21:ncol(demuxalot)])
    sd <- unlist(sd)
    sd <- unname(sd)
    res <- colnames(demuxalot[,1:20])
    res <- c(res)
    res <- gsub(".*_","",res)
    demuxalot <- data.frame(mean, sd, res)
    demuxalot <- na.omit(demuxalot)
    demuxalot$class <- "Demuxalot"

    ## Vireo NSC
    vireo <- read.xlsx('~/ensemblux_manuscript/Figure5/ADHD_NSC_vireo_500/clustering_ARI.xlsx')
    vireo <- data.frame(vireo)
    mean <- list(vireo[,1:20])
    mean <- unlist(mean)
    mean <- unname(mean)
    sd <- list(vireo[,21:ncol(vireo)])
    sd <- unlist(sd)
    sd <- unname(sd)
    res <- colnames(vireo[,1:20])
    res <- c(res)
    res <- gsub(".*_","",res)
    vireo <- data.frame(mean, sd, res)
    vireo <- na.omit(vireo)
    vireo$class <- "Vireo"

    ## Souporcell NSC
    souporcell <- read.xlsx('~/ensemblux_manuscript/Figure5/ADHD_NSC_souporcell_500/clustering_ARI.xlsx')
    souporcell <- data.frame(souporcell)
    mean <- list(souporcell[,1:20])
    mean <- unlist(mean)
    mean <- unname(mean)
    sd <- list(souporcell[,21:ncol(souporcell)])
    sd <- unlist(sd)
    sd <- unname(sd)
    res <- colnames(souporcell[,1:20])
    res <- c(res)
    res <- gsub(".*_","",res)
    souporcell <- data.frame(mean, sd, res)
    souporcell <- na.omit(souporcell)
    souporcell$class <- "Souporcell"

    ## Dataframe 
    bind <- rbind(ensemblux, demuxlet, none, doubletfinder, demuxalot, vireo, souporcell)
    bind$class <- factor(bind$class, levels = c("Ensemblux", "Demuxalot", "Demuxlet", "Souporcell", "Vireo", "DF", "None"))
    bind_all <- bind

    ## Compute mean and quantile for boxplot
    df1 <- bind_all %>% 
    group_by(class) %>% 
    summarize(d_ymin = min(mean),
            d_ymax = max(mean),
            d_lower = quantile(mean, 0.25),
            d_middle = mean(mean),
            d_upper = quantile(mean, 0.75)) %>% as.data.frame()

    df1$class <- factor(df1$class, levels = c("Ensemblux", "Demuxalot", "Demuxlet", "Souporcell", "Vireo", "DF", "None"))

    ## Plot
    ggplot(df1) + 
        geom_boxplot(aes(x = class,
                        ymin = d_ymin,
                        lower = d_lower,
                        middle = d_middle,
                        upper = d_upper,
                        ymax = d_ymax,
                        colour = class), stat = "identity") + theme_classic() +
            theme(axis.title.y = element_text(size = 12, face = "bold"),
            axis.title.x = element_blank(), 
            axis.text.x = element_text(size = 12, colour = "black", angle = 45, hjust =1),
            axis.text.y = element_text(size = 12, colour = "black"),
            legend.position = "none") + 
            scale_colour_manual(values = c("black","#d95f02", "#e6ab02", "#7570b3", "#66a61e", "dodgerblue2", "grey63")) +
            ylab("Adjusted Rand Index") + xlab(("Clustering resolution")) +
            scale_x_discrete(labels = c("Ensemblux", "Demuxalot",  "Demuxlet", "Souporcell", "Vireo-GT", "DoubletFinder", "All droplets"))
    ggsave("~/ensemblux_manuscript/Figure5_ADHD/ADHD_ARI_alltool_500_NSC_2.pdf",width = 3.25, height = 3)


    ## Compute ANOVA
    res_aov <- aov(mean ~ class,
    data = bind_all)
    oneway.test(mean ~ class,
    data = bind_all,
    var.equal = TRUE)  

##

#########################################################################
# Ensemblux putative doublets assigned as singlets by constituent tools #
#########################################################################
## code
    ## Load Seurat object
    seu_int<-readRDS("~/ensemblux_manuscript/Figure6/NSC_annotated_seurat.rds")
 
    ## Create Seurat matadata dataframe
    bind_meta <- data.frame(seu_int@meta.data)
    bind_meta <- bind_meta %>% dplyr::select(Ensemblux_assignment, vireo_assignment, souporcell_assignment, demuxlet_assignment, demuxalot_assignment)

    ## Souporcell
    par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_souporcell_500/meta.csv"
    meta_data <- read.delim(par_metadata, header = T, sep = ",") 
    bind_meta_temp <- bind_meta
    bind_meta_temp <- subset(bind_meta_temp, Ensemblux_assignment == "doublet" & souporcell_assignment != "doublet" )
    bind_meta_temp <- subset(bind_meta_temp, souporcell_assignment != "unassigned")
    bind_meta_temp <- merge(bind_meta_temp, meta_data, by = "souporcell_assignment")
    one <- data.frame(table(bind_meta_temp$DiseaseStatus))
    
    bind_meta_temp <- bind_meta
    bind_meta_temp <- subset(bind_meta_temp, souporcell_assignment != "doublet" )
    bind_meta_temp <- subset(bind_meta_temp, souporcell_assignment != "unassigned")
    bind_meta_temp <- merge(bind_meta_temp, meta_data, by = "souporcell_assignment")
    two <- data.frame(table(bind_meta_temp$DiseaseStatus))
    two
    three <- cbind(one, two)
    three$prop <- three[,2]/three[,4]
    three <- three[,c(3,5)]
    three$tool <- "souporcell"
    souporcell_df <- three

    ## Demuxalot
    par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_demuxalot_500/meta.csv"
    meta_data <- read.delim(par_metadata, header = T, sep = ",") 
    bind_meta_temp <- bind_meta
    bind_meta_temp <- subset(bind_meta_temp, Ensemblux_assignment == "doublet" & demuxalot_assignment != "doublet" )
    bind_meta_temp <- subset(bind_meta_temp, demuxalot_assignment != "unassigned")
    bind_meta_temp <- merge(bind_meta_temp, meta_data, by = "demuxalot_assignment")
    one <- data.frame(table(bind_meta_temp$DiseaseStatus))
    
    bind_meta_temp <- bind_meta
    bind_meta_temp <- subset(bind_meta_temp, demuxalot_assignment != "doublet" )
    bind_meta_temp <- subset(bind_meta_temp, demuxalot_assignment != "unassigned")
    bind_meta_temp <- merge(bind_meta_temp, meta_data, by = "demuxalot_assignment")
    two <- data.frame(table(bind_meta_temp$DiseaseStatus))
    two
    three <- cbind(one, two)
    three$prop <- three[,2]/three[,4]
    three <- three[,c(3,5)]
    three$tool <- "demuxalot"
    demuxalot_df <- three

    ## Demuxlet
    par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_demuxlet_500/meta.csv"
    meta_data <- read.delim(par_metadata, header = T, sep = ",") 
    bind_meta_temp <- bind_meta
    bind_meta_temp <- subset(bind_meta_temp, Ensemblux_assignment == "doublet" & demuxlet_assignment != "doublet" )
    bind_meta_temp <- subset(bind_meta_temp, demuxlet_assignment != "unassigned")
    bind_meta_temp <- merge(bind_meta_temp, meta_data, by = "demuxlet_assignment")
    one <- data.frame(table(bind_meta_temp$DiseaseStatus))
    
    bind_meta_temp <- bind_meta
    bind_meta_temp <- subset(bind_meta_temp, demuxlet_assignment != "doublet" )
    bind_meta_temp <- subset(bind_meta_temp, demuxlet_assignment != "unassigned")
    bind_meta_temp <- merge(bind_meta_temp, meta_data, by = "demuxlet_assignment")
    two <- data.frame(table(bind_meta_temp$DiseaseStatus))
    two
    three <- cbind(one, two)
    three$prop <- three[,2]/three[,4]
    three <- three[,c(3,5)]
    three$tool <- "demuxlet"
    demuxlet_df <- three

    ## Vireo
    par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_vireo_500/meta.csv"
    meta_data <- read.delim(par_metadata, header = T, sep = ",") 
    bind_meta_temp <- bind_meta
    bind_meta_temp <- subset(bind_meta_temp, Ensemblux_assignment == "doublet" & vireo_assignment != "doublet" )
    bind_meta_temp <- subset(bind_meta_temp, vireo_assignment != "unassigned")
    bind_meta_temp <- merge(bind_meta_temp, meta_data, by = "vireo_assignment")
    one <- data.frame(table(bind_meta_temp$DiseaseStatus))
    
    bind_meta_temp <- bind_meta
    bind_meta_temp <- subset(bind_meta_temp, vireo_assignment != "doublet" )
    bind_meta_temp <- subset(bind_meta_temp, vireo_assignment != "unassigned")
    bind_meta_temp <- merge(bind_meta_temp, meta_data, by = "vireo_assignment")
    two <- data.frame(table(bind_meta_temp$DiseaseStatus))
    two
    three <- cbind(one, two)
    three$prop <- three[,2]/three[,4]
    three <- three[,c(3,5)]
    three$tool <- "vireo"
    vireo_df <- three

    ## Dataframe
    merge_df <- rbind(souporcell_df, demuxalot_df, demuxlet_df, vireo_df)
    merge_df$tool <- factor(merge_df$tool, levels = c('demuxalot', 'demuxlet', 'souporcell', 'vireo'))

    ## Plot
    ggplot(merge_df, aes(y = prop, x = Var1, fill = Var1)) +
        geom_bar(stat = "identity") +
        theme_bw() + 
        theme(axis.text.x = element_blank(),
            axis.ticks.x = element_blank(),
            axis.text.y = element_text(size = 12, colour = "black"),
            axis.title.x = element_blank(), 
            axis.title.y = element_text(size = 12, face = "bold"),
            legend.position = "none",
            panel.grid = element_blank(), 
            strip.background=element_blank()
            ) + 
        scale_fill_manual(values = c("indianred3", "dodgerblue2")) +
        scale_y_continuous(limits = c(0,0.5)) + 
        ylab("Proportion of cells\nwithin disorder status") + 
        facet_wrap(~tool, ncol = 4)
    ggsave(paste(output_dir,"/Ensemblux_dub_as_sing_NSC.pdf", sep=""), width = 4, height = 2.75)
##

#######################################################################
# Compute DEG with MAST using Sample labels from demultiplexing tools #
#######################################################################
## code
    ############
    # Demuxlet #
    ############
    ## code
        output_dir= '~/ensemblux_manuscript/Figure6/ADHD_NSC_demuxlet_500_MAST'
        dir.create(output_dir)
        par_merge_meta <- "demuxlet_assignment"
        par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_demuxlet_500/meta.csv"
                                                    
        seu_int<-readRDS("~/ensemblux_manuscript/Figure6/NSC_annotated_seurat.rds")
        nrow(seu_int@meta.data)
        
        seu_int[["RNA3"]] <- as(object = seu_int[["RNA"]], Class = "Assay")
        DefaultAssay(seu_int) <- "RNA3"

        ensemblux_r1 <- read.delim("~/NSC/pool1/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r1) <- paste0("Pool1_", ensemblux_r1$barcode)
        rownames(ensemblux_r1) == rownames(df_r1)
        ensemblux_r2 <- read.delim("~/NSC/pool2/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r2) <- paste0("Pool2_", ensemblux_r2$barcode)
        rownames(ensemblux_r2) == rownames(df_r2)

        bind_meta <- rbind(ensemblux_r1, ensemblux_r2)

        seu_int <- AddMetaData(seu_int, bind_meta)
        nrow(seu_int@meta.data)

        unique(seu_int@meta.data$demuxlet_assignment)
            
            xx <- unique(seu_int@meta.data$demuxlet_assignment)
            xx <- xx[!xx %in% c("unassigned", "doublet")]

            Idents(seu_int) <- "demuxlet_assignment"
            seu_int=subset(seu_int,idents=xx)

        unique(seu_int@meta.data$demuxlet_assignment) 
        nrow(seu_int@meta.data)

        meta_data <- read.delim(par_metadata, header = T, sep = ",") 
        new_meta <- colnames(meta_data)

        metadata_df <- data.frame(seu_int@meta.data)

        merge_metadata_df <- merge(metadata_df,meta_data, by = par_merge_meta )
        df<- merge_metadata_df[,new_meta]                          ## new
        nrow(metadata_df) == nrow(df)

        colnames <- colnames(df)

        for (i in 1:ncol(df)){
        seu_int <- AddMetaData(seu_int, metadata = df[,i], col.name = colnames[i])
        }

        dd<-read.csv('~/ensemblux_manuscript/Figure6/NSC_contrast.txt', sep="")

        OUT_dir_sample <- paste(output_dir,"/Cell_based_celltype_groups",sep='') 
        dir.create(OUT_dir_sample)

        for(i in 1:nrow(dd)){  
        dir.create(paste(OUT_dir_sample,"/",dd[i,1],sep=''))
        }

        test <- data.frame(seu_int@meta.data)
        nrow(test)
        table(test$DiseaseStatus)
        table(test$DiseaseStatus, test$resolution_0.25_broad_refined_DEG)

        par_statistical_method <- "MAST"

        for(i in 1:nrow(dd)){
        Idents(seu_int) <- dd[i,2]    
        celltype.sub.seu <- subset(seu_int, idents = dd[i,3])
        Idents(celltype.sub.seu) <- dd[i,4]    
        DGE <- FindMarkers(celltype.sub.seu, ident.1 = dd[i,5], ident.2 = dd[i,6],  logfc.threshold = 0, test.use = par_statistical_method)
        write.csv(DGE, file = paste(OUT_dir_sample,"/",dd[i,1],"/", dd[i,1],'_DEG.csv', sep=""), quote = FALSE, sep = ",")
        }

        unique(seu_int@meta.data$resolution_0.25_fine)
        Idents(seu_int) <- 'resolution_0.25_broad_refined_DEG'

        DimPlot(seu_int, reduction = "umap", label = FALSE, pt.size = 0.1, raster = FALSE) 
        ggsave(file = paste(output_dir, "/resolution_0.25_broad_refined_DEG.pdf", sep=''))
    ##
    ############
    # Demuxalot #
    ############
    ## code
        output_dir= '~/ensemblux_manuscript/Figure6/ADHD_NSC_demuxalot_500_MAST'
        dir.create(output_dir)
        par_merge_meta <- "demuxalot_assignment"
        par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_demuxalot_500/meta.csv"
                                                    
        seu_int<-readRDS("~/ensemblux_manuscript/Figure6/NSC_annotated_seurat.rds")
        nrow(seu_int@meta.data)
        
        seu_int[["RNA3"]] <- as(object = seu_int[["RNA"]], Class = "Assay")
        DefaultAssay(seu_int) <- "RNA3"

        ensemblux_r1 <- read.delim("~/NSC/pool1/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r1) <- paste0("Pool1_", ensemblux_r1$barcode)
        rownames(ensemblux_r1) == rownames(df_r1)
        ensemblux_r2 <- read.delim("~/NSC/pool2/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r2) <- paste0("Pool2_", ensemblux_r2$barcode)
        rownames(ensemblux_r2) == rownames(df_r2)

        bind_meta <- rbind(ensemblux_r1, ensemblux_r2)

        seu_int <- AddMetaData(seu_int, bind_meta)
        nrow(seu_int@meta.data)

        unique(seu_int@meta.data$demuxalot_assignment)
            
            xx <- unique(seu_int@meta.data$demuxalot_assignment)
            xx <- xx[!xx %in% c("unassigned", "doublet")]

            Idents(seu_int) <- "demuxalot_assignment"
            seu_int=subset(seu_int,idents=xx)

        unique(seu_int@meta.data$demuxalot_assignment) 
        nrow(seu_int@meta.data)

        meta_data <- read.delim(par_metadata, header = T, sep = ",") 
        new_meta <- colnames(meta_data)

        metadata_df <- data.frame(seu_int@meta.data)

        merge_metadata_df <- merge(metadata_df,meta_data, by = par_merge_meta )
        df<- merge_metadata_df[,new_meta]                        
        nrow(metadata_df) == nrow(df)

        colnames <- colnames(df)

        for (i in 1:ncol(df)){
        seu_int <- AddMetaData(seu_int, metadata = df[,i], col.name = colnames[i])
        }

        dd<-read.csv('~/ensemblux_manuscript/Figure6/NSC_contrast.txt', sep="")

        OUT_dir_sample <- paste(output_dir,"/Cell_based_celltype_groups",sep='') 
        dir.create(OUT_dir_sample)

        for(i in 1:nrow(dd)){  
        dir.create(paste(OUT_dir_sample,"/",dd[i,1],sep=''))
        }

        test <- data.frame(seu_int@meta.data)
        nrow(test)
        table(test$DiseaseStatus)
        table(test$DiseaseStatus, test$resolution_0.25_broad_refined_DEG)

        par_statistical_method <- "MAST"

        for(i in 1:nrow(dd)){
        Idents(seu_int) <- dd[i,2]    
        celltype.sub.seu <- subset(seu_int, idents = dd[i,3])
        Idents(celltype.sub.seu) <- dd[i,4]    
        DGE <- FindMarkers(celltype.sub.seu, ident.1 = dd[i,5], ident.2 = dd[i,6],  logfc.threshold = 0, test.use = par_statistical_method)
        write.csv(DGE, file = paste(OUT_dir_sample,"/",dd[i,1],"/", dd[i,1],'_DEG.csv', sep=""), quote = FALSE, sep = ",")
        }

        unique(seu_int@meta.data$resolution_0.25_fine)
        Idents(seu_int) <- 'resolution_0.25_broad_refined_DEG'

        DimPlot(seu_int, reduction = "umap", label = FALSE, pt.size = 0.1, raster = FALSE) 
        ggsave(file = paste(output_dir, "/resolution_0.25_broad_refined_DEG.pdf", sep=''))
    ##
    ############
    # Souporcell #
    ############
    ## code
        output_dir= '~/ensemblux_manuscript/Figure6/ADHD_NSC_souporcell_500_MAST'
        dir.create(output_dir)
        par_merge_meta <- "souporcell_assignment"
        par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_souporcell_500/meta.csv"
                                                    
        seu_int<-readRDS("~/ensemblux_manuscript/Figure6/NSC_annotated_seurat.rds")
        nrow(seu_int@meta.data)
        
        seu_int[["RNA3"]] <- as(object = seu_int[["RNA"]], Class = "Assay")
        DefaultAssay(seu_int) <- "RNA3"

        ensemblux_r1 <- read.delim("~/NSC/pool1/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r1) <- paste0("Pool1_", ensemblux_r1$barcode)
        rownames(ensemblux_r1) == rownames(df_r1)
        ensemblux_r2 <- read.delim("~/NSC/pool2/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r2) <- paste0("Pool2_", ensemblux_r2$barcode)
        rownames(ensemblux_r2) == rownames(df_r2)

        bind_meta <- rbind(ensemblux_r1, ensemblux_r2)

        seu_int <- AddMetaData(seu_int, bind_meta)
        nrow(seu_int@meta.data)

        unique(seu_int@meta.data$souporcell_assignment)
            
            xx <- unique(seu_int@meta.data$souporcell_assignment)
            xx <- xx[!xx %in% c("unassigned", "doublet")]

            Idents(seu_int) <- "souporcell_assignment"
            seu_int=subset(seu_int,idents=xx)

        unique(seu_int@meta.data$souporcell_assignment) 
        nrow(seu_int@meta.data)

        meta_data <- read.delim(par_metadata, header = T, sep = ",") 
        new_meta <- colnames(meta_data)

        metadata_df <- data.frame(seu_int@meta.data)

        merge_metadata_df <- merge(metadata_df,meta_data, by = par_merge_meta )
        df<- merge_metadata_df[,new_meta]                          ## new
        nrow(metadata_df) == nrow(df)

        colnames <- colnames(df)

        for (i in 1:ncol(df)){
        seu_int <- AddMetaData(seu_int, metadata = df[,i], col.name = colnames[i])
        }

        dd<-read.csv('~/ensemblux_manuscript/Figure6/NSC_contrast.txt', sep="")

        OUT_dir_sample <- paste(output_dir,"/Cell_based_celltype_groups",sep='') 
        dir.create(OUT_dir_sample)

        for(i in 1:nrow(dd)){  
        dir.create(paste(OUT_dir_sample,"/",dd[i,1],sep=''))
        }

        test <- data.frame(seu_int@meta.data)
        nrow(test)
        table(test$DiseaseStatus)
        table(test$DiseaseStatus, test$resolution_0.25_broad_refined_DEG)

        par_statistical_method <- "MAST"

        for(i in 1:nrow(dd)){
        Idents(seu_int) <- dd[i,2]    
        celltype.sub.seu <- subset(seu_int, idents = dd[i,3])
        Idents(celltype.sub.seu) <- dd[i,4]    
        DGE <- FindMarkers(celltype.sub.seu, ident.1 = dd[i,5], ident.2 = dd[i,6],  logfc.threshold = 0, test.use = par_statistical_method)
        write.csv(DGE, file = paste(OUT_dir_sample,"/",dd[i,1],"/", dd[i,1],'_DEG.csv', sep=""), quote = FALSE, sep = ",")
        }

        unique(seu_int@meta.data$resolution_0.25_fine)
        Idents(seu_int) <- 'resolution_0.25_broad_refined_DEG'

        DimPlot(seu_int, reduction = "umap", label = FALSE, pt.size = 0.1, raster = FALSE) 
        ggsave(file = paste(output_dir, "/resolution_0.25_broad_refined_DEG.pdf", sep=''))
    ##
    ############
    # Vireo #
    ############
    ## code
        output_dir= '~/ensemblux_manuscript/Figure6/ADHD_NSC_vireo_500_MAST'
        dir.create(output_dir)
        par_merge_meta <- "vireo_assignment"
        par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_vireo_500/meta.csv"
                                                    
        seu_int<-readRDS("~/ensemblux_manuscript/Figure6/NSC_annotated_seurat.rds")
        nrow(seu_int@meta.data)
        
        seu_int[["RNA3"]] <- as(object = seu_int[["RNA"]], Class = "Assay")
        DefaultAssay(seu_int) <- "RNA3"

        ensemblux_r1 <- read.delim("~/NSC/pool1/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r1) <- paste0("Pool1_", ensemblux_r1$barcode)
        rownames(ensemblux_r1) == rownames(df_r1)
        ensemblux_r2 <- read.delim("~/NSC/pool2/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r2) <- paste0("Pool2_", ensemblux_r2$barcode)
        rownames(ensemblux_r2) == rownames(df_r2)

        bind_meta <- rbind(ensemblux_r1, ensemblux_r2)

        seu_int <- AddMetaData(seu_int, bind_meta)
        nrow(seu_int@meta.data)

        unique(seu_int@meta.data$vireo_assignment)
            
            xx <- unique(seu_int@meta.data$vireo_assignment)
            xx <- xx[!xx %in% c("unassigned", "doublet")]

            Idents(seu_int) <- "vireo_assignment"
            seu_int=subset(seu_int,idents=xx)

        unique(seu_int@meta.data$vireo_assignment) 
        nrow(seu_int@meta.data)

        meta_data <- read.delim(par_metadata, header = T, sep = ",") 
        new_meta <- colnames(meta_data)

        metadata_df <- data.frame(seu_int@meta.data)

        merge_metadata_df <- merge(metadata_df,meta_data, by = par_merge_meta )
        df<- merge_metadata_df[,new_meta]                          ## new
        nrow(metadata_df) == nrow(df)

        colnames <- colnames(df)

        for (i in 1:ncol(df)){
        seu_int <- AddMetaData(seu_int, metadata = df[,i], col.name = colnames[i])
        }

        dd<-read.csv('~/ensemblux_manuscript/Figure6/NSC_contrast.txt', sep="")

        OUT_dir_sample <- paste(output_dir,"/Cell_based_celltype_groups",sep='') 
        dir.create(OUT_dir_sample)

        for(i in 1:nrow(dd)){  
        dir.create(paste(OUT_dir_sample,"/",dd[i,1],sep=''))
        }

        test <- data.frame(seu_int@meta.data)
        nrow(test)
        table(test$DiseaseStatus)
        table(test$DiseaseStatus, test$resolution_0.25_broad_refined_DEG)

        par_statistical_method <- "MAST"

        for(i in 1:nrow(dd)){
        Idents(seu_int) <- dd[i,2]    
        celltype.sub.seu <- subset(seu_int, idents = dd[i,3])
        Idents(celltype.sub.seu) <- dd[i,4]    
        DGE <- FindMarkers(celltype.sub.seu, ident.1 = dd[i,5], ident.2 = dd[i,6],  logfc.threshold = 0, test.use = par_statistical_method)
        write.csv(DGE, file = paste(OUT_dir_sample,"/",dd[i,1],"/", dd[i,1],'_DEG.csv', sep=""), quote = FALSE, sep = ",")
        }

        unique(seu_int@meta.data$resolution_0.25_fine)
        Idents(seu_int) <- 'resolution_0.25_broad_refined_DEG'

        DimPlot(seu_int, reduction = "umap", label = FALSE, pt.size = 0.1, raster = FALSE) 
        ggsave(file = paste(output_dir, "/resolution_0.25_broad_refined_DEG.pdf", sep=''))
    ##
    ############
    # Ensemblux #
    ############
    ## code
        output_dir= '~/ensemblux_manuscript/Figure6/ADHD_NSC_ensemblux_500_MAST'
        dir.create(output_dir)
        par_merge_meta <- "ensemblux_assignment"
        par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_ensemblux_500/meta.csv"
                                                    
        seu_int<-readRDS("~/ensemblux_manuscript/Figure6/NSC_annotated_seurat.rds")
        nrow(seu_int@meta.data)
        
        seu_int[["RNA3"]] <- as(object = seu_int[["RNA"]], Class = "Assay")
        DefaultAssay(seu_int) <- "RNA3"

        ensemblux_r1 <- read.delim("~/NSC/pool1/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r1) <- paste0("Pool1_", ensemblux_r1$barcode)
        rownames(ensemblux_r1) == rownames(df_r1)
        ensemblux_r2 <- read.delim("~/NSC/pool2/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r2) <- paste0("Pool2_", ensemblux_r2$barcode)
        rownames(ensemblux_r2) == rownames(df_r2)

        bind_meta <- rbind(ensemblux_r1, ensemblux_r2)

        seu_int <- AddMetaData(seu_int, bind_meta)
        nrow(seu_int@meta.data)

        unique(seu_int@meta.data$Ensemblux_assignment)
            
            xx <- unique(seu_int@meta.data$Ensemblux_assignment)
            xx <- xx[!xx %in% c("unassigned", "doublet")]

            Idents(seu_int) <- "Ensemblux_assignment"
            seu_int=subset(seu_int,idents=xx)

        unique(seu_int@meta.data$Ensemblux_assignment) 
        nrow(seu_int@meta.data)

        meta_data <- read.delim(par_metadata, header = T, sep = ",") 
        new_meta <- colnames(meta_data)

        metadata_df <- data.frame(seu_int@meta.data)

        merge_metadata_df <- merge(metadata_df,meta_data, by = par_merge_meta )
        df<- merge_metadata_df[,new_meta]                          ## new
        nrow(metadata_df) == nrow(df)

        colnames <- colnames(df)

        for (i in 1:ncol(df)){
        seu_int <- AddMetaData(seu_int, metadata = df[,i], col.name = colnames[i])
        }

        dd<-read.csv('~/ensemblux_manuscript/Figure6/NSC_contrast.txt', sep="")

        OUT_dir_sample <- paste(output_dir,"/Cell_based_celltype_groups",sep='') 
        dir.create(OUT_dir_sample)

        for(i in 1:nrow(dd)){  
        dir.create(paste(OUT_dir_sample,"/",dd[i,1],sep=''))
        }

        test <- data.frame(seu_int@meta.data)
        nrow(test)
        table(test$DiseaseStatus)
        table(test$DiseaseStatus, test$resolution_0.25_broad_refined_DEG)

        par_statistical_method <- "MAST"

        for(i in 1:nrow(dd)){
        Idents(seu_int) <- dd[i,2]    
        celltype.sub.seu <- subset(seu_int, idents = dd[i,3])
        Idents(celltype.sub.seu) <- dd[i,4]    
        DGE <- FindMarkers(celltype.sub.seu, ident.1 = dd[i,5], ident.2 = dd[i,6],  logfc.threshold = 0, test.use = par_statistical_method)
        write.csv(DGE, file = paste(OUT_dir_sample,"/",dd[i,1],"/", dd[i,1],'_DEG.csv', sep=""), quote = FALSE, sep = ",")
        }

        unique(seu_int@meta.data$resolution_0.25_fine)
        Idents(seu_int) <- 'resolution_0.25_broad_refined_DEG'

        DimPlot(seu_int, reduction = "umap", label = FALSE, pt.size = 0.1, raster = FALSE) 
        ggsave(file = paste(output_dir, "/resolution_0.25_broad_refined_DEG.pdf", sep=''))
    ##
##

####################################################################################################################
# Compute DEG with MAST using Sample labels from demultiplexing tools after removal of Ensemblux putative doublets #
####################################################################################################################
## code
    ############
    # Demuxlet #
    ############
    ## code
        output_dir= '~/ensemblux_manuscript/Figure6/ADHD_NSC_demuxlet_Ensemblux_doublets_500_MAST'
        dir.create(output_dir)
        par_merge_meta <- "demuxlet_assignment"
        par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_demuxlet_500/meta.csv"
                                                    
        seu_int<-readRDS("~/ensemblux_manuscript/Figure6/NSC_annotated_seurat.rds")
        nrow(seu_int@meta.data)
        
        seu_int[["RNA3"]] <- as(object = seu_int[["RNA"]], Class = "Assay")
        DefaultAssay(seu_int) <- "RNA3"

        ensemblux_r1 <- read.delim("~/NSC/pool1/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r1) <- paste0("Pool1_", ensemblux_r1$barcode)
        rownames(ensemblux_r1) == rownames(df_r1)
        ensemblux_r2 <- read.delim("~/NSC/pool2/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r2) <- paste0("Pool2_", ensemblux_r2$barcode)
        rownames(ensemblux_r2) == rownames(df_r2)

        bind_meta <- rbind(ensemblux_r1, ensemblux_r2)
        seu_int <- AddMetaData(seu_int, bind_meta)

        unique(seu_int@meta.data$Ensemblux_assignment)
            xx <- unique(seu_int@meta.data$Ensemblux_assignment)
            xx <- xx[!xx %in% c("doublet")]

            Idents(seu_int) <- "Ensemblux_assignment"
            seu_int=subset(seu_int,idents=xx)
        unique(seu_int@meta.data$Ensemblux_assignment) 

        unique(seu_int@meta.data$demuxlet_assignment)
            xx <- unique(seu_int@meta.data$demuxlet_assignment)
            xx <- xx[!xx %in% c("doublet", "unassigned")]

            Idents(seu_int) <- "demuxlet_assignment"
            seu_int=subset(seu_int,idents=xx)
        unique(seu_int@meta.data$demuxlet_assignment) 

        meta_data <- read.delim(par_metadata, header = T, sep = ",") 
        new_meta <- colnames(meta_data)

        metadata_df <- data.frame(seu_int@meta.data)

        merge_metadata_df <- merge(metadata_df,meta_data, by = par_merge_meta )
        df<- merge_metadata_df[,new_meta]                          ## new
        nrow(metadata_df) == nrow(df)

        colnames <- colnames(df)
        nrow(df)

        for (i in 1:ncol(df)){
        seu_int <- AddMetaData(seu_int, metadata = df[,i], col.name = colnames[i])
        }

        dd<-read.csv('~/ensemblux_manuscript/Figure6/NSC_contrast.txt', sep="")

        OUT_dir_sample <- paste(output_dir,"/Cell_based_celltype_groups",sep='') 
        dir.create(OUT_dir_sample)

        for(i in 1:nrow(dd)){  
        dir.create(paste(OUT_dir_sample,"/",dd[i,1],sep=''))
        }

        par_statistical_method <- "MAST"

        for(i in 1:nrow(dd)){
        Idents(seu_int) <- dd[i,2]    
        celltype.sub.seu <- subset(seu_int, idents = dd[i,3])
        Idents(celltype.sub.seu) <- dd[i,4]    
        DGE <- FindMarkers(celltype.sub.seu, ident.1 = dd[i,5], ident.2 = dd[i,6],  logfc.threshold = 0, test.use = par_statistical_method)
        write.csv(DGE, file = paste(OUT_dir_sample,"/",dd[i,1],"/", dd[i,1],'_DEG.csv', sep=""), quote = FALSE, sep = ",")
        }

        Idents(seu_int) <- 'resolution_0.25_broad_refined_DEG'

        DimPlot(seu_int, reduction = "umap", label = FALSE, pt.size = 0.1, raster = FALSE) 
        ggsave(file = paste(output_dir, "/resolution_0.25_broad_refined_DEG.pdf", sep=''))
    ##
    ############
    # Demuxalot #
    ############
    ## code
        output_dir= '~/ensemblux_manuscript/Figure6/ADHD_NSC_demuxalot_Ensemblux_doublets_500_MAST'
        dir.create(output_dir)
        par_merge_meta <- "demuxalot_assignment"
        par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_demuxalot_500/meta.csv"
                                                    
        seu_int<-readRDS("~/ensemblux_manuscript/Figure6/NSC_annotated_seurat.rds")
        nrow(seu_int@meta.data)
        
        seu_int[["RNA3"]] <- as(object = seu_int[["RNA"]], Class = "Assay")
        DefaultAssay(seu_int) <- "RNA3"

        ensemblux_r1 <- read.delim("~/NSC/pool1/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r1) <- paste0("Pool1_", ensemblux_r1$barcode)
        rownames(ensemblux_r1) == rownames(df_r1)
        ensemblux_r2 <- read.delim("~/NSC/pool2/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r2) <- paste0("Pool2_", ensemblux_r2$barcode)
        rownames(ensemblux_r2) == rownames(df_r2)

        bind_meta <- rbind(ensemblux_r1, ensemblux_r2)
        seu_int <- AddMetaData(seu_int, bind_meta)

        unique(seu_int@meta.data$Ensemblux_assignment)
            xx <- unique(seu_int@meta.data$Ensemblux_assignment)
            xx <- xx[!xx %in% c("doublet")]

            Idents(seu_int) <- "Ensemblux_assignment"
            seu_int=subset(seu_int,idents=xx)
        unique(seu_int@meta.data$Ensemblux_assignment) 

        unique(seu_int@meta.data$demuxalot_assignment)
            xx <- unique(seu_int@meta.data$demuxalot_assignment)
            xx <- xx[!xx %in% c("doublet", "unassigned")]

            Idents(seu_int) <- "demuxalot_assignment"
            seu_int=subset(seu_int,idents=xx)
        unique(seu_int@meta.data$demuxalot_assignment) 

        meta_data <- read.delim(par_metadata, header = T, sep = ",") 
        new_meta <- colnames(meta_data)

        metadata_df <- data.frame(seu_int@meta.data)

        merge_metadata_df <- merge(metadata_df,meta_data, by = par_merge_meta )
        df<- merge_metadata_df[,new_meta]                          ## new
        nrow(metadata_df) == nrow(df)

        colnames <- colnames(df)
        nrow(df)

        for (i in 1:ncol(df)){
        seu_int <- AddMetaData(seu_int, metadata = df[,i], col.name = colnames[i])
        }

        dd<-read.csv('~/ensemblux_manuscript/Figure6/NSC_contrast.txt', sep="")

        OUT_dir_sample <- paste(output_dir,"/Cell_based_celltype_groups",sep='') 
        dir.create(OUT_dir_sample)

        for(i in 1:nrow(dd)){  
        dir.create(paste(OUT_dir_sample,"/",dd[i,1],sep=''))
        }

        par_statistical_method <- "MAST"

        for(i in 1:nrow(dd)){
        Idents(seu_int) <- dd[i,2]    
        celltype.sub.seu <- subset(seu_int, idents = dd[i,3])
        Idents(celltype.sub.seu) <- dd[i,4]    
        DGE <- FindMarkers(celltype.sub.seu, ident.1 = dd[i,5], ident.2 = dd[i,6],  logfc.threshold = 0, test.use = par_statistical_method)
        write.csv(DGE, file = paste(OUT_dir_sample,"/",dd[i,1],"/", dd[i,1],'_DEG.csv', sep=""), quote = FALSE, sep = ",")
        }

        Idents(seu_int) <- 'resolution_0.25_broad_refined_DEG'

        DimPlot(seu_int, reduction = "umap", label = FALSE, pt.size = 0.1, raster = FALSE) 
        ggsave(file = paste(output_dir, "/resolution_0.25_broad_refined_DEG.pdf", sep=''))
    ##
    ############
    # Souporcell #
    ############
    ## code
        output_dir= '~/ensemblux_manuscript/Figure6/ADHD_NSC_souporcell_Ensemblux_doublets_500_MAST'
        dir.create(output_dir)
        par_merge_meta <- "souporcell_assignment"
        par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_souporcell_500/meta.csv"
                                                    
        seu_int<-readRDS("~/ensemblux_manuscript/Figure6/NSC_annotated_seurat.rds")
        nrow(seu_int@meta.data)
        
        seu_int[["RNA3"]] <- as(object = seu_int[["RNA"]], Class = "Assay")
        DefaultAssay(seu_int) <- "RNA3"

        ensemblux_r1 <- read.delim("~/NSC/pool1/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r1) <- paste0("Pool1_", ensemblux_r1$barcode)
        rownames(ensemblux_r1) == rownames(df_r1)
        ensemblux_r2 <- read.delim("~/NSC/pool2/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r2) <- paste0("Pool2_", ensemblux_r2$barcode)
        rownames(ensemblux_r2) == rownames(df_r2)

        bind_meta <- rbind(ensemblux_r1, ensemblux_r2)
        seu_int <- AddMetaData(seu_int, bind_meta)

        unique(seu_int@meta.data$Ensemblux_assignment)
            xx <- unique(seu_int@meta.data$Ensemblux_assignment)
            xx <- xx[!xx %in% c("doublet")]

            Idents(seu_int) <- "Ensemblux_assignment"
            seu_int=subset(seu_int,idents=xx)
        unique(seu_int@meta.data$Ensemblux_assignment) 

        unique(seu_int@meta.data$souporcell_assignment)
            xx <- unique(seu_int@meta.data$souporcell_assignment)
            xx <- xx[!xx %in% c("doublet", "unassigned")]

            Idents(seu_int) <- "souporcell_assignment"
            seu_int=subset(seu_int,idents=xx)
        unique(seu_int@meta.data$souporcell_assignment) 

        meta_data <- read.delim(par_metadata, header = T, sep = ",") 
        new_meta <- colnames(meta_data)

        metadata_df <- data.frame(seu_int@meta.data)

        merge_metadata_df <- merge(metadata_df,meta_data, by = par_merge_meta )
        df<- merge_metadata_df[,new_meta]                          ## new
        nrow(metadata_df) == nrow(df)

        colnames <- colnames(df)
        nrow(df)

        for (i in 1:ncol(df)){
        seu_int <- AddMetaData(seu_int, metadata = df[,i], col.name = colnames[i])
        }

        dd<-read.csv('~/ensemblux_manuscript/Figure6/NSC_contrast.txt', sep="")

        OUT_dir_sample <- paste(output_dir,"/Cell_based_celltype_groups",sep='') 
        dir.create(OUT_dir_sample)

        for(i in 1:nrow(dd)){  
        dir.create(paste(OUT_dir_sample,"/",dd[i,1],sep=''))
        }

        par_statistical_method <- "MAST"

        for(i in 1:nrow(dd)){
        Idents(seu_int) <- dd[i,2]    
        celltype.sub.seu <- subset(seu_int, idents = dd[i,3])
        Idents(celltype.sub.seu) <- dd[i,4]    
        DGE <- FindMarkers(celltype.sub.seu, ident.1 = dd[i,5], ident.2 = dd[i,6],  logfc.threshold = 0, test.use = par_statistical_method)
        write.csv(DGE, file = paste(OUT_dir_sample,"/",dd[i,1],"/", dd[i,1],'_DEG.csv', sep=""), quote = FALSE, sep = ",")
        }

        Idents(seu_int) <- 'resolution_0.25_broad_refined_DEG'

        DimPlot(seu_int, reduction = "umap", label = FALSE, pt.size = 0.1, raster = FALSE) 
        ggsave(file = paste(output_dir, "/resolution_0.25_broad_refined_DEG.pdf", sep=''))
    ##
    ############
    # Vireo #
    ############
    ## code
        output_dir= '~/ensemblux_manuscript/Figure6/ADHD_NSC_vireo_Ensemblux_doublets_500_MAST'
        dir.create(output_dir)
        par_merge_meta <- "vireo_assignment"
        par_metadata <- "~/ensemblux_manuscript/Figure6/ADHD_NSC_vireo_500/meta.csv"
                                                    
        seu_int<-readRDS("~/ensemblux_manuscript/Figure6/NSC_annotated_seurat.rds")
        nrow(seu_int@meta.data)
        
        seu_int[["RNA3"]] <- as(object = seu_int[["RNA"]], Class = "Assay")
        DefaultAssay(seu_int) <- "RNA3"

        ensemblux_r1 <- read.delim("~/NSC/pool1/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r1) <- paste0("Pool1_", ensemblux_r1$barcode)
        rownames(ensemblux_r1) == rownames(df_r1)
        ensemblux_r2 <- read.delim("~/NSC/pool2/Ensemblux/confidence/confidence_PWE_GBD_EID_droplet_assignment.csv", header = T, sep = ",")
        rownames(ensemblux_r2) <- paste0("Pool2_", ensemblux_r2$barcode)
        rownames(ensemblux_r2) == rownames(df_r2)

        bind_meta <- rbind(ensemblux_r1, ensemblux_r2)
        seu_int <- AddMetaData(seu_int, bind_meta)

        unique(seu_int@meta.data$Ensemblux_assignment)
            xx <- unique(seu_int@meta.data$Ensemblux_assignment)
            xx <- xx[!xx %in% c("doublet")]

            Idents(seu_int) <- "Ensemblux_assignment"
            seu_int=subset(seu_int,idents=xx)
        unique(seu_int@meta.data$Ensemblux_assignment) 

        unique(seu_int@meta.data$vireo_assignment)
            xx <- unique(seu_int@meta.data$vireo_assignment)
            xx <- xx[!xx %in% c("doublet", "unassigned")]

            Idents(seu_int) <- "vireo_assignment"
            seu_int=subset(seu_int,idents=xx)
        unique(seu_int@meta.data$vireo_assignment) 

        meta_data <- read.delim(par_metadata, header = T, sep = ",") 
        new_meta <- colnames(meta_data)

        metadata_df <- data.frame(seu_int@meta.data)

        merge_metadata_df <- merge(metadata_df,meta_data, by = par_merge_meta )
        df<- merge_metadata_df[,new_meta]                          ## new
        nrow(metadata_df) == nrow(df)

        colnames <- colnames(df)
        nrow(df)

        for (i in 1:ncol(df)){
        seu_int <- AddMetaData(seu_int, metadata = df[,i], col.name = colnames[i])
        }

        dd<-read.csv('~/ensemblux_manuscript/Figure6/NSC_contrast.txt', sep="")

        OUT_dir_sample <- paste(output_dir,"/Cell_based_celltype_groups",sep='') 
        dir.create(OUT_dir_sample)

        for(i in 1:nrow(dd)){  
        dir.create(paste(OUT_dir_sample,"/",dd[i,1],sep=''))
        }

        par_statistical_method <- "MAST"

        for(i in 1:nrow(dd)){
        Idents(seu_int) <- dd[i,2]    
        celltype.sub.seu <- subset(seu_int, idents = dd[i,3])
        Idents(celltype.sub.seu) <- dd[i,4]    
        DGE <- FindMarkers(celltype.sub.seu, ident.1 = dd[i,5], ident.2 = dd[i,6],  logfc.threshold = 0, test.use = par_statistical_method)
        write.csv(DGE, file = paste(OUT_dir_sample,"/",dd[i,1],"/", dd[i,1],'_DEG.csv', sep=""), quote = FALSE, sep = ",")
        }

        Idents(seu_int) <- 'resolution_0.25_broad_refined_DEG'

        DimPlot(seu_int, reduction = "umap", label = FALSE, pt.size = 0.1, raster = FALSE) 
        ggsave(file = paste(output_dir, "/resolution_0.25_broad_refined_DEG.pdf", sep=''))
    ##
##

###################
# Plot DEG counts #
###################
## code
    ### Load in and process DEG outputs
    #############
    # Ensemblux #
    #############
    ## code
        cell_based_cell_types <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")
        t = "Ensemblux"
        list <- list()

        for(i in unique(cell_based_cell_types)){        
        list[i] <- list(read.delim(paste0("~/MAST_NSC/",t,"/Cell_based_celltype_groups/", i,"/", i,"_DEG.csv"), header = T, sep = ","))
        }

        list2env(list,envir=.GlobalEnv)

        CellType_df <- list(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)

        names(CellType_df) <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")

        cols_keep <- c("X","p_val","avg_log2FC","p_val_adj")

        list_CellBased <- list()

        for (i in unique(names(CellType_df))){
        j <- data.frame(CellType_df[i])
        colnames(j) <- c("X", "p_val", "avg_log2FC", "pct.1", "pct.2", "p_val_adj")
        j <- j[,colnames(j) %in% cols_keep]
        if (nrow(j > 0)){
            j$cell_type <- paste0(i)
            j$method <- "cell_based"
            list_CellBased[i] <- list(j)
        }else{
            print(paste0("did not find any DEGs for ", i))
        }
        list_CellBased[i]
        }

        list_CellBased_Ensemblux <- list_CellBased
        list2env(list_CellBased,envir=.GlobalEnv)
        bind_cell_based <- rbind(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)
        bind_cell_based$tool <- t
        Ensemblux_df <- bind_cell_based
    ##
    ##############
    # Demuxalot #
    ##############
    ## code
        cell_based_cell_types <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")
        t = "Demuxalot"
        list <- list()

        for(i in unique(cell_based_cell_types)){        
        list[i] <- list(read.delim(paste0("~/MAST_NSC/",t,"/Cell_based_celltype_groups/", i,"/", i,"_DEG.csv"), header = T, sep = ","))
        }

        list2env(list,envir=.GlobalEnv)

        CellType_df <- list(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)

        names(CellType_df) <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")

        cols_keep <- c("X","p_val","avg_log2FC","p_val_adj")

        list_CellBased <- list()

        for (i in unique(names(CellType_df))){
        j <- data.frame(CellType_df[i])
        colnames(j) <- c("X", "p_val", "avg_log2FC", "pct.1", "pct.2", "p_val_adj")
        j <- j[,colnames(j) %in% cols_keep]
        if (nrow(j > 0)){
            j$cell_type <- paste0(i)
            j$method <- "cell_based"
            list_CellBased[i] <- list(j)
        }else{
            print(paste0("did not find any DEGs for ", i))
        }
        list_CellBased[i]
        }

        list_CellBased_Demuxalot <- list_CellBased
        list2env(list_CellBased,envir=.GlobalEnv)
        bind_cell_based <- rbind(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)
        bind_cell_based$tool <- t
        Demuxalot_df <- bind_cell_based
    ##
    #############################################
    # Demuxalot with Ensemblux doublets removed #
    #############################################
    ## code
        cell_based_cell_types <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")
        t = "Demuxalot_ens"
        list <- list()

        for(i in unique(cell_based_cell_types)){        
        list[i] <- list(read.delim(paste0("~/MAST_NSC/",t,"/Cell_based_celltype_groups/", i,"/", i,"_DEG.csv"), header = T, sep = ","))
        }

        list2env(list,envir=.GlobalEnv)

        CellType_df <- list(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)

        names(CellType_df) <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")

        cols_keep <- c("X","p_val","avg_log2FC","p_val_adj")

        list_CellBased <- list()

        for (i in unique(names(CellType_df))){
        j <- data.frame(CellType_df[i])
        colnames(j) <- c("X", "p_val", "avg_log2FC", "pct.1", "pct.2", "p_val_adj")
        j <- j[,colnames(j) %in% cols_keep]
        if (nrow(j > 0)){
            j$cell_type <- paste0(i)
            j$method <- "cell_based"
            list_CellBased[i] <- list(j)
        }else{
            print(paste0("did not find any DEGs for ", i))
        }
        list_CellBased[i]
        }

        list_CellBased_Demuxalot_ens <- list_CellBased
        list2env(list_CellBased,envir=.GlobalEnv)
        bind_cell_based <- rbind(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)
        bind_cell_based$tool <- t
        Demuxalot_ens_df <- bind_cell_based
    ##
    ##############
    # Souporcell #
    ##############
    ## code
        cell_based_cell_types <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")
        t = "Souporcell"
        list <- list()

        for(i in unique(cell_based_cell_types)){        
        list[i] <- list(read.delim(paste0("~/MAST_NSC/",t,"/Cell_based_celltype_groups/", i,"/", i,"_DEG.csv"), header = T, sep = ","))
        }

        list2env(list,envir=.GlobalEnv)

        CellType_df <- list(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)

        names(CellType_df) <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")

        cols_keep <- c("X","p_val","avg_log2FC","p_val_adj")

        list_CellBased <- list()

        for (i in unique(names(CellType_df))){
        j <- data.frame(CellType_df[i])
        colnames(j) <- c("X", "p_val", "avg_log2FC", "pct.1", "pct.2", "p_val_adj")
        j <- j[,colnames(j) %in% cols_keep]
        if (nrow(j > 0)){
            j$cell_type <- paste0(i)
            j$method <- "cell_based"
            list_CellBased[i] <- list(j)
        }else{
            print(paste0("did not find any DEGs for ", i))
        }
        list_CellBased[i]
        }

        list_CellBased_Souporcell <- list_CellBased
        list2env(list_CellBased,envir=.GlobalEnv)
        bind_cell_based <- rbind(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)
        bind_cell_based$tool <- t
        Souporcell_df <- bind_cell_based
    ##
    #############################################
    # Souporcell with Ensemblux doublets removed #
    #############################################
    ## code
        cell_based_cell_types <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")
        t = "Souporcell_ens"
        list <- list()

        for(i in unique(cell_based_cell_types)){        
        list[i] <- list(read.delim(paste0("~/MAST_NSC/",t,"/Cell_based_celltype_groups/", i,"/", i,"_DEG.csv"), header = T, sep = ","))
        }

        list2env(list,envir=.GlobalEnv)

        CellType_df <- list(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)

        names(CellType_df) <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")

        cols_keep <- c("X","p_val","avg_log2FC","p_val_adj")

        list_CellBased <- list()

        for (i in unique(names(CellType_df))){
        j <- data.frame(CellType_df[i])
        colnames(j) <- c("X", "p_val", "avg_log2FC", "pct.1", "pct.2", "p_val_adj")
        j <- j[,colnames(j) %in% cols_keep]
        if (nrow(j > 0)){
            j$cell_type <- paste0(i)
            j$method <- "cell_based"
            list_CellBased[i] <- list(j)
        }else{
            print(paste0("did not find any DEGs for ", i))
        }
        list_CellBased[i]
        }

        list_CellBased_Souporcell_ens <- list_CellBased
        list2env(list_CellBased,envir=.GlobalEnv)
        bind_cell_based <- rbind(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)
        bind_cell_based$tool <- t
        Souporcell_ens_df <- bind_cell_based
    ##
    #########
    # Vireo #
    #########
    ## code
        cell_based_cell_types <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")
        t = "Vireo"
        list <- list()

        for(i in unique(cell_based_cell_types)){        
        list[i] <- list(read.delim(paste0("~/MAST_NSC/",t,"/Cell_based_celltype_groups/", i,"/", i,"_DEG.csv"), header = T, sep = ","))
        }

        list2env(list,envir=.GlobalEnv)

        CellType_df <- list(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)

        names(CellType_df) <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")

        cols_keep <- c("X","p_val","avg_log2FC","p_val_adj")

        list_CellBased <- list()

        for (i in unique(names(CellType_df))){
        j <- data.frame(CellType_df[i])
        colnames(j) <- c("X", "p_val", "avg_log2FC", "pct.1", "pct.2", "p_val_adj")
        j <- j[,colnames(j) %in% cols_keep]
        if (nrow(j > 0)){
            j$cell_type <- paste0(i)
            j$method <- "cell_based"
            list_CellBased[i] <- list(j)
        }else{
            print(paste0("did not find any DEGs for ", i))
        }
        list_CellBased[i]
        }

        list_CellBased_Vireo <- list_CellBased
        list2env(list_CellBased,envir=.GlobalEnv)
        bind_cell_based <- rbind(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)
        bind_cell_based$tool <- t
        Vireo_df <- bind_cell_based
    ##
    #########################################
    # Vireo with Ensemblux doublets removed #
    #########################################
    ## code
        cell_based_cell_types <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")
        t = "Vireo_ens"
        list <- list()

        for(i in unique(cell_based_cell_types)){        
        list[i] <- list(read.delim(paste0("~/MAST_NSC/",t,"/Cell_based_celltype_groups/", i,"/", i,"_DEG.csv"), header = T, sep = ","))
        }

        list2env(list,envir=.GlobalEnv)

        CellType_df <- list(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)

        names(CellType_df) <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")

        cols_keep <- c("X","p_val","avg_log2FC","p_val_adj")

        list_CellBased <- list()

        for (i in unique(names(CellType_df))){
        j <- data.frame(CellType_df[i])
        colnames(j) <- c("X", "p_val", "avg_log2FC", "pct.1", "pct.2", "p_val_adj")
        j <- j[,colnames(j) %in% cols_keep]
        if (nrow(j > 0)){
            j$cell_type <- paste0(i)
            j$method <- "cell_based"
            list_CellBased[i] <- list(j)
        }else{
            print(paste0("did not find any DEGs for ", i))
        }
        list_CellBased[i]
        }

        list_CellBased_Vireo_ens <- list_CellBased
        list2env(list_CellBased,envir=.GlobalEnv)
        bind_cell_based <- rbind(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)
        bind_cell_based$tool <- t
        Vireo_ens_df <- bind_cell_based
    ##
    ############
    # Demuxlet #
    ############
    ## code
        cell_based_cell_types <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")
        t = "Demuxlet"
        list <- list()

        for(i in unique(cell_based_cell_types)){        
        list[i] <- list(read.delim(paste0("~/MAST_NSC/",t,"/Cell_based_celltype_groups/", i,"/", i,"_DEG.csv"), header = T, sep = ","))
        }

        list2env(list,envir=.GlobalEnv)

        CellType_df <- list(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)

        names(CellType_df) <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")

        cols_keep <- c("X","p_val","avg_log2FC","p_val_adj")

        list_CellBased <- list()

        for (i in unique(names(CellType_df))){
        j <- data.frame(CellType_df[i])
        colnames(j) <- c("X", "p_val", "avg_log2FC", "pct.1", "pct.2", "p_val_adj")
        j <- j[,colnames(j) %in% cols_keep]
        if (nrow(j > 0)){
            j$cell_type <- paste0(i)
            j$method <- "cell_based"
            list_CellBased[i] <- list(j)
        }else{
            print(paste0("did not find any DEGs for ", i))
        }
        list_CellBased[i]
        }

        list_CellBased_Demuxlet <- list_CellBased
        list2env(list_CellBased,envir=.GlobalEnv)
        bind_cell_based <- rbind(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)
        bind_cell_based$tool <- t
        Demuxlet_df <- bind_cell_based
    ##
    ############################################
    # Demuxlet with Ensemblux doublets removed #
    ############################################
    ## code
        cell_based_cell_types <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")
        t = "Demuxlet_ens"
        list <- list()

        for(i in unique(cell_based_cell_types)){        
        list[i] <- list(read.delim(paste0("~/MAST_NSC/",t,"/Cell_based_celltype_groups/", i,"/", i,"_DEG.csv"), header = T, sep = ","))
        }

        list2env(list,envir=.GlobalEnv)

        CellType_df <- list(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)

        names(CellType_df) <- c("Glia", "NSC_SOX2", "NPC_POU5F1", "Neurons_DCX", "Neurons_GRIA1", "NPC_S100B", "NPC_MEF2C", "NSC_APOA1")

        cols_keep <- c("X","p_val","avg_log2FC","p_val_adj")

        list_CellBased <- list()

        for (i in unique(names(CellType_df))){
        j <- data.frame(CellType_df[i])
        colnames(j) <- c("X", "p_val", "avg_log2FC", "pct.1", "pct.2", "p_val_adj")
        j <- j[,colnames(j) %in% cols_keep]
        if (nrow(j > 0)){
            j$cell_type <- paste0(i)
            j$method <- "cell_based"
            list_CellBased[i] <- list(j)
        }else{
            print(paste0("did not find any DEGs for ", i))
        }
        list_CellBased[i]
        }

        list_CellBased_Demuxlet_ens <- list_CellBased
        list2env(list_CellBased,envir=.GlobalEnv)
        bind_cell_based <- rbind(Glia, NSC_SOX2, NPC_POU5F1, Neurons_DCX, Neurons_GRIA1, NPC_S100B, NPC_MEF2C, NSC_APOA1)
        bind_cell_based$tool <- t
        Demuxlet_ens_df <- bind_cell_based
    ##
    ############################################
    # Plot DEG counts for demultiplexing tools #
    ############################################
    ## code
        temp_df <- rbind( Ensemblux_df, Demuxalot_df, Demuxlet_df,  Souporcell_df, Vireo_df)
        temp_df <- subset(temp_df, p_val_adj <= 0.01 & abs(avg_log2FC) >= 0.5 )
        temp_df$tool <- factor(temp_df$tool, levels = c( "Ensemblux", "Demuxalot",  "Demuxlet", "Souporcell",  "Vireo"))
        temp_df <- subset(temp_df, X != "fill")

        table_df <- table(temp_df$cell_type,temp_df$tool )
        table_df <- data.frame(table_df)
        table_df$Var1 <- factor(table_df$Var1, levels = c('Fibroblasts', 'NSC', 'Progenitors', 'Neurons', 'Neurons_Ex', 'NPC_glia','NPC','NSC_vasculature'))

        ggplot(table_df, aes(fill=Freq, y=Var2, x=Var1, label = Freq )) + 
            geom_tile() +
            geom_text()+
            theme_bw() +
            theme(axis.title.y = element_text(face = "bold", size = 12),
                    axis.title.x = element_blank(),
                    axis.text.y = element_text(size = 12, colour = "black"),
                    axis.text.x = element_text(angle = 45, hjust = 1),
                    axis.line.x = element_blank(),
                    axis.ticks.x = element_blank(),
                    legend.position = "none") +
            ylab("Number of DEGs") +
            scale_fill_gradient(low = "white", high = "indianred3") +
            scale_y_discrete(expand = c(0,0)) +
            scale_x_discrete(expand = c(0,0)) 
    ##
    ################################################################################
    # Plot DEG counts for demultiplexing tools after removal of Ensemblux doublets #
    ################################################################################
    ## code
        temp_df <- rbind( Ensemblux_df, Demuxalot_ens_df,  Demuxlet_ens_df,  Vireo_ens_df, Souporcell_ens_df)
        temp_df <- subset(temp_df, p_val_adj <= 0.01 & abs(avg_log2FC) >= 0.5 )
        temp_df$tool <- factor(temp_df$tool, levels = c( "Ensemblux", "Demuxalot_ens",  "Demuxlet_ens", "Souporcell_ens",  "Vireo_ens"))
        temp_df <- subset(temp_df, X != "fill")

        table_df <- table(temp_df$cell_type,temp_df$tool )
        table_df <- data.frame(table_df)
        table_df$Var1 <- factor(table_df$Var1, levels = c('Fibroblasts', 'NSC', 'Progenitors', 'Neurons', 'Neurons_Ex', 'NPC_glia','NPC','NSC_vasculature'))

        ggplot(table_df, aes(fill=Freq, y=Var2, x=Var1, label = Freq )) + 
            geom_tile() +
            geom_text()+
            theme_bw() +
            theme(axis.title.y = element_text(face = "bold", size = 12),
                    axis.title.x = element_blank(),
                    axis.text.y = element_text(size = 12, colour = "black"),
                    axis.text.x = element_text(angle = 45, hjust = 1),
                    axis.line.x = element_blank(),
                    axis.ticks.x = element_blank(),
                    legend.position = "none") +
            ylab("Number of DEGs") +
            scale_fill_gradient(low = "white", high = "indianred3") +
            scale_y_discrete(expand = c(0,0), labels = c("Ensemblux", "Demuxalot", "Demuxlet", "Souporcell","Vireo")) +
            scale_x_discrete(expand = c(0,0)) 
    ##

